"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-17

Creates all tables from the SQLAlchemy models. Subsequent schema changes
should be autogenerated (`alembic revision --autogenerate`).
"""
from alembic import op

from app.database import Base
from app import models  # noqa: F401  (populate metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
